import base64

template_ui_b64 = '''ICAgICAgICB7LyogVGVtcGxhdGUgb3B0aW9ucyAoYWRtaW4gb25seSkgKi99CiAgICAgICAge3VzZXJSb2xlID09PSAiYWRtaW4iICYmICgKICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJmbGV4IGZsZXgtY29sIGdhcC00IGJvcmRlci10IHB0LTQiPgogICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTIiPgogICAgICAgICAgICAgIDxDaGVja2JveAogICAgICAgICAgICAgICAgaWQ9ImlzLXRlbXBsYXRlIgogICAgICAgICAgICAgICAgY2hlY2tlZD17YWdlbnQuaXNUZW1wbGF0ZSB8fCBmYWxzZX0KICAgICAgICAgICAgICAgIG9uQ2hlY2tlZENoYW5nZT17KGNoZWNrZWQpID0+IHNldEFnZW50KHsgaXNUZW1wbGF0ZTogY2hlY2tlZCBhcyBib29sZWFuIH0pfQogICAgICAgICAgICAgICAgZGlzYWJsZWQ9e2lzTG9hZGluZyB8fCAhaGFzRWRpdEFjY2Vzc30KICAgICAgICAgICAgICA8L0NoZWNrYm94PgogICAgICAgICAgICAgIDxMYWJlbCBodG1sRm9yPSJpcy10ZW1wbGF0ZSIgY2xhc3NOYW1lPSJjdXJzb3ItcG9pbnRlciI+CiAgICAgICAgICAgICAgICDlj5HluIPkuLrmqKHmnb/liLDmmbrog73kvZPllYblupcKICAgICAgICAgICAgIDwvTGFiZWw+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICB7YWdlbnQuaXNUZW1wbGF0ZSAmJiBjYXRlZ29yaWVzICYmIGNhdGVnb3JpZXMubGVuZ3RoID4gMCAmJiAoCiAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImZsZXggZmxleC1jb2wgZ2FwLTIiPgogICAgICAgICAgICAgICAgPExhYmVsIGh0bWxGb3I9InRlbXBsYXRlLWNhdGVnb3J5Ij7mqIHmnb/liYbnsvjvvInlj6/plJ4pPC9MYWJlbD4KICAgICAgICAgICAgICAgIDxzZWxlY3QKICAgICAgICAgICAgICAgICAgIGlkPSJ0ZW1wbGF0ZS1jYXRlZ29yeSIKICAgICAgICAgICAgICAgICAgIHZhbHVlPXthZ2VudC5jYXRlZ29yeUlkIHx8ICIifQogICAgICAgICAgICAgICAgICAgb25DaGFuZ2U9eyhlKSA9PiBzZXRBZ2VudCh7IGNhdGVnb3J5SWQ6IGUudGFyZ2V0LnZhbHVlIHx8IG51bGwgfSl9CiAgICAgICAgICAgICAgICAgICBkaXNhYmxlZD17aXNMb2FkaW5nIHx8ICFoYXNFZGl0QWNjZXNzfQogICAgICAgICAgICAgICAgICAgY2xhc3NOYW1lPSJmbGV4IGgtMTAgdy1mdWxsIHJvdW5kZWQtbWQgYm9yZGVyIGJvcmRlci1pbnB1dCBiZy1iYWNrZ3JvdW5kIHB4LTMgcHktMiB0ZXh0LXNtIGZvY3VzLXZpc2libGU6b3V0bGluZS1ub25lIGZvY3VzLXZpc2libGU6cmluZy0yIGZvY3VzLXZpc2libGU6cmluZy1yaW5nIgogICAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iIj7kuI3pgInmi6nliIbnsbvvvIjmmL7npLrlnKgi5YWo6YOoIuagh+etvuS4i++8iTwvb3B0aW9uPgogICAgICAgICAgICAgICAgICB7Y2F0ZWdvcmllcy5tYXAoKGNhdGVnb3J5KSA9PiAoCiAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiBrZXk9e2NhdGVnb3J5LmlkfSB2YWx1ZT17Y2F0ZWdvcnkuaWR9PgogICAgICAgICAgICAgICAgICAgICAge2NhdGVnb3J5LmVtb2ppfSB7Y2F0ZWdvcnkubmFtZX0KICAgICAgICAgICAgICAgICAgICA8L29wdGlvbj4KICAgICAgICAgICAgICAgICAgKX0KICAgICAgICAgICAgICAgIDwvc2VsZWN0PgogICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICB9KQogICAgICAgICAgPC9kaXY+CiAgICAgICApfQo='''

template_ui = base64.b64decode(template_ui_b64).decode('utf-8')

# Read file
with open('src/components/agent/edit-agent.tsx', 'r') as f:
    lines = f.readlines()

# Find insertion point (before agent-tool-bindings section)
insert_idx = None
for i, line in enumerate(lines):
    if 'agent-tool-bindings' in line and i > 400:
        insert_idx = i - 2
        break

if insert_idx:
    lines.insert(insert_idx, template_ui + '\n')
    with open('src/components/agent/edit-agent.tsx', 'w') as f:
        f.writelines(lines)
    print(f'Template UI inserted at line {insert_idx + 1}')
else:
    print('Insertion point not found')
