#!/bin/bash
echo "=== 功能需求自动规划 ==="
echo ""
echo "提供需求格式："
echo "  ## 需求概述: [一句话]"
echo "  ## 核心功能: [列表]"
echo "  ## 约束条件: [技术限制/必须复用]"
echo ""
echo "Claude 会自动："
echo "  1. 生成详细任务清单"
echo "  2. 识别依赖关系"
echo "  3. 按优先级排序"
echo "  4. 执行前确认"
echo ""
